# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pr:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  outputFolder: '../../artifacts'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- script: dotnet --version
  displayName: Show dotnet version

- task: DotNetCoreCLI@2
  displayName: 'Build AsyncMethodNameFixer'
  inputs:
    command: 'build'
    projects: 'AsyncMethodNameFixer/AsyncMethodNameFixer/AsyncMethodNameFixer.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(outputFolder)'

- task: DotNetCoreCLI@2
  displayName: 'Test AsyncMethodNameFixer'
  inputs:
    command: 'test'
    projects: 'AsyncMethodNameFixer/AsyncMethodNameFixer.Test/AsyncMethodNameFixer.Test.csproj'
    testRunTitle: 'Tests'

- task: MSBuild@1
  displayName: 'Create Vsix'
  inputs:
    solution: 'AsyncMethodNameFixer/AsyncMethodNameFixer.Vsix/AsyncMethodNameFixer.Vsix.csproj'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArguments: '/p:OutputPath=$(outputFolder)'

- task: CopyFiles@2
  displayName: 'Copy Nuget Package'
  inputs:
    SourceFolder: '$(outputFolder)'
    Contents: '**\*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\Nuget'
    CleanTargetFolder: true
    OverWrite: true

- task: CopyFiles@2
  displayName: 'Copy Vsix Package'
  inputs:
    SourceFolder: '$(outputFolder)'
    Contents: '**\*.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\Vsix'
    CleanTargetFolder: true
    OverWrite: true
