# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetCommand@2
  displayName: 'Restoring Packages'
  inputs:
    command: 'restore'
    solution: 'AsyncMethodNameFixer.sln'
    selectOrConfig: 'config'

- task: VSBuild@1
  displayName: 'Building'
  inputs:
    solution: 'AsyncMethodNameFixer.sln'
    vsVersion: '16.0'
    configuration: '$(buildConfiguration)'
    clean: true
    restoreNugetPackages: true
    msbuildArchitecture: 'x64'
